### ISSUE TITLE
Kernel crash with stacktrace

### ISSUE THREAD

**Issue by gnull** [ryan4yin/nixos-rk3588#61] opened 2024-10-22 21:35 UTC
I just had the kernel crash on OPi5 Plus.

I booted, edited `flake.nix` with Vim and ran `nixos-rebuild --flake .`, and after a minute or two the kernel crashed with [this](https://gist.github.com/gnull/24565bd6551c5d4ef75427884df2982d) log. Should this be reported in armbian?

I had the kernel spam as in #37 and disabled it with `dmesg -n 1` at boot. The log shows spam getting through after the stacktrace, maybe related or not — I don't know.

I'm using the current master head b95bb58af82e65af8f2ecdec829f74143958a49c.

Ivan

**Comment by ryan4yin** [comment] 2024-10-24 12:40
My understanding of the Linux kernel is not deep, and I can't quite figure out the cause of your issue either. 
However, I just merged #60, which includes updates to the kernel and nixpkgs with numerous improvements. You can try updating your flake inputs to see if it helps.

**Closed as completed** 2024-12-06 16:00 UTC
